name: images downloader

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Clone pre repositories
      run: |
        ls
        echo '------------------------------'
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd ./source/assets/images/
        
        git rm -rf tensorflow_cookbook
        git commit -m "remove all the pics"
        echo "----------------------------------"
        echo "print the current work directory:"
        ls
        cd ../../../
        git push origin master
        
        
        cd source/assets/images/
        mkdir book_images
        cd book_images/
        ls
        echo '============================================'
        wget -O ErrorHandling.zip https://onlineconvertfree.com/upload/converter/220920/VCdm1ug/TensorFlow_Machine_Learning_Cookbook.tiff
        unzip ErrorHandling.zip
        git add -A
        git commit -m "Add some photos "
        cd ../../../../
        ls
        git push origin master
